import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/Footer'
import Providers from '@/app/providers'
import {Poppins,K2D} from 'next/font/google'
interface LandingProps {}
const k2d = K2D({subsets: ['latin'], weight: '400'})
const poppins = Poppins({subsets: ["latin"], weight: '400'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      <body className={`${k2d.className} dark:bg-slate-900`}>
        <Providers>
        <Navbar />
        <div className='bg-slate-50 dark:bg-slate-900  transition-all ease-in-out duration-200 '>

        {children}
        </div>
        <div className='box'>

        <Footer />
        </div>
        </Providers>
      </body>
    </html>
  )
}
