import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Footer from '@/components/Footer'
import Providers from '@/app/providers'

const poppins = Poppins({subsets: ["latin"], weight: '400'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      <body className={poppins.className}>
        <Providers>
        <Navbar />
        <div className='bg-slate-50 dark:bg-slate-900  transition-all ease-in-out duration-200 '>

        {children}
        </div>
        {/* <Footer /> */}
        </Providers>
      </body>
    </html>
  )
}
